on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of OpenLiberty to generate blog for, e.g. 22.0.0.9, 22.0.0.9-beta'
        required: true
        type: string
      publish-date:
        description: 'Date of publish of the blog, format: YYYY-MM-DD'
        required: true
        default: '2050-01-01'
        type: string
      author-name:
        description: 'Name of the anthor'
        required: true
        # default: ${{ github.actor }}
        type: string
      github-username:
        description: 'GitHub username of the anthor'
        required: true
        # default: ${{ github.actor }}
        type: string

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  ListIssues:
    name: Automate release and beta blog PR creation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: prod

      - name: Create blog
        run: |
          # git switch -c ${{ inputs.version }}
          wget 'https://raw.githubusercontent.com/thallium/summer-project-blogs/master/main.py'
          python3 main.py ${{ inputs.version }} ${{ inputs.publish-date }} ${{ inputs.author-name }} ${{ inputs.github-username }}
          rm main.py

      - name: Generate draft URL
        id: gen-url
        run:
          echo "::set-output name=url::https://draft-blogs-openlibertyio.mybluemix.net/blog/$(echo ${{ inputs.publish-date }} | tr - /)/${{ inputs.version }}.html"

      - name: Create PR
        id: create-pr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: ${{ inputs.version }}
          branch: ${{ inputs.version }}
          base: staging
          title: ${{ inputs.version }}
          assignees: ${{ github.actor }}
          body: "Preview draft at: ${{ steps.gen-url.outputs.url }}"
          # TODO put links in the body
          
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Send Slack alert
        run: |
          python3 .github/workflows/slack_alert.py \
          ${{ inputs.version }} ${{ inputs.publish-date }} ${{ inputs.author-name }} ${{ inputs.github-username }} \
          ${{ steps.create-pr.outputs.pull-request-number }} ${{ steps.gen-url.outputs.url }} "https://hooks.slack.com/services/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"
