on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of OpenLiberty to generate blog for, e.g. 22.0.0.9, 22.0.0.9-beta'
        required: true
        type: string
      publish-date:
        description: 'Date of publish of the blog, format: YYYY-MM-DD'
        required: true
        default: '2050-01-01'
        type: string
      author-name:
        description: 'Name of the author, put the name in quotes if the name contains space'
        required: true
        # default: ${{ github.actor }}
        type: string
      github-username:
        description: 'GitHub username of the author'
        required: true
        # default: ${{ github.actor }}
        type: string

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  create_blog_and_pr:
    name: Automate release and beta blog PR creation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: prod

      - name: Create blog
        run: |
          python3 .github/workflows/gen_blog.py ${{ inputs.version }} ${{ inputs.publish-date }} ${{ inputs.author-name }} ${{ inputs.github-username }}

      - name: Generate draft URL
        id: gen-url
        run: |
          echo "::set-output name=draft-url::https://draft-blogs-openlibertyio.mybluemix.net/blog/$(echo ${{ inputs.publish-date }} | tr - /)/${{ inputs.version }}.html"
          echo "::set-output name=staging-url::https://staging-blogs-openlibertyio.mybluemix.net/blog/$(echo ${{ inputs.publish-date }} | tr - /)/${{ inputs.version }}.html"

      - name: Create PR to draft
        id: create-pr-draft
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: ${{ inputs.version }}
          branch: ${{ inputs.version }}-draft
          base: draft
          title: ${{ inputs.version }} draft
          assignees: ${{ github.actor }}
          body: "Preview at draft site: ${{ steps.gen-url.outputs.draft-url }}"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: prod

      - name: Create blog
        id: gen-blog
        run: |
          python3 .github/workflows/gen_blog.py ${{ inputs.version }} ${{ inputs.publish-date }} ${{ inputs.author-name }} ${{ inputs.github-username }}

      - name: Create PR to staging
        id: create-pr-staging
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: ${{ inputs.version }}
          branch: ${{ inputs.version }}-staging
          base: staging
          title: ${{ inputs.version }} staging
          assignees: ${{ github.actor }}
          body: "Preview at draft site: ${{ steps.gen-url.outputs.draft-url }}\nPreview at staging site: ${{ steps.gen-url.outputs.staging-url }}"
          reviewers: ${{ steps.gen-blog.outputs.reviewers }}
          draft: true

      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Send Slack alert
        run: |
          python3 .github/workflows/slack_alert.py \
          ${{ inputs.version }} ${{ inputs.publish-date }} ${{ inputs.author-name }} ${{ inputs.github-username }} \
          ${{ steps.create-pr-draft.outputs.pull-request-number }} ${{ steps.gen-url.outputs.draft-url }} ${{ secrets.SLACK_HOOK }} 
